---
# IMPORTANT: Change settings here, but DO NOT change the spacing.
# Remove comments and add values where applicable.
# The descriptions below should be self-explanatory

title: "Question Two"
#subtitle: "This will appear as Right Header"

documentclass: "elsarticle"

# --------- Thesis title (Optional - set to FALSE by default).
# You can move the details below around as you please.
Thesis_FP: FALSE
# Entry1: "An unbelievable study with a title spanning multiple lines."
# Entry2: "\\textbf{Nico Katzke}" # textbf for bold
# Entry3: "A thesis submitted toward the degree of Doctor of Philosophy"
# Uni_Logo: Tex/Logo.png # Place a logo in the indicated location (from your root, e.g. defaults to ~/Tex/Logo.png) and uncomment this line. Leave uncommented for no image
# Logo_width: 0.3 # If using a logo - use this to set width (size) of image
# Entry4: "Under the supervision of: \\vfill Prof. Joe Smith and Dr. Frank Smith"
# Entry5: "Stellenbosch University"
# Entry6: April 2020
# Entry7:
# Entry8:

# --------- Front Page
# Comment: ----- Follow this pattern for up to 5 authors
AddTitle: TRUE # Use FALSE when submitting to peer reviewed platform. This will remove author names.
Author1: "Jessica Van der Berg"  # First Author - note the thanks message displayed as an italic footnote of first page.
Ref1: "Financial Econometrics, 2021" # First Author's Affiliation
Email1: "20190565\\@sun.ac.za" # First Author's Email address


# Comment out below to remove both. JEL Codes only given if keywords also given.
keywords: "Question2\\sep Finance \\sep Financial Econometrics" # Use \\sep to separate
JELCodes: "L250 \\sep L100"

# ----- Manage headers and footers:
#BottomLFooter: $Title$
#BottomCFooter:
#TopLHeader: \leftmark # Adds section name at topleft. Remove comment to add it.
BottomRFooter: "\\footnotesize Page \\thepage" # Add a '#' before this line to remove footer.
addtoprule: TRUE
addfootrule: TRUE               # Use if footers added. Add '#' to remove line.

# --------- page margins:
margin: 2.3 # Sides
bottom: 2 # bottom
top: 2.5 # Top
HardSet_layout: TRUE # Hard-set the spacing of words in your document. This will stop LaTeX squashing text to fit on pages, e.g.
# This is done by hard-setting the spacing dimensions. Set to FALSE if you want LaTeX to optimize this for your paper.

# --------- Line numbers
linenumbers: FALSE # Used when submitting to journal

# ---------- References settings:
# You can download cls format here: https://www.zotero.org/ - simply search for your institution. You can also edit and save cls formats here: https://editor.citationstyles.org/about/
# Hit download, store it in Tex/ folder, and change reference below - easy.
bibliography: Tex/ref.bib       # Do not edit: Keep this naming convention and location.
csl: Tex/harvard-stellenbosch-university.csl # referencing format used.
# By default, the bibliography only displays the cited references. If you want to change this, you can comment out one of the following:
#nocite: '@*' # Add all items in bibliography, whether cited or not
# nocite: |  # add specific references that aren't cited
#  @grinold2000
#  @Someoneelse2010

# ---------- General:
RemovePreprintSubmittedTo: TRUE  # Removes the 'preprint submitted to...' at bottom of titlepage
Journal: "Journal of Finance"   # Journal that the paper will be submitting to, if RemovePreprintSubmittedTo is set to TRUE.
toc: FALSE                       # Add a table of contents
numbersections: TRUE             # Should sections (and thus figures and tables) be numbered?
fontsize: 11pt                  # Set fontsize
linestretch: 1.2                # Set distance between lines.
link-citations: TRUE            # This creates dynamic links to the papers in reference list.

### Adding additional latex packages:
# header-includes:
#    - \usepackage{colortbl} # Add additional packages here.

output:
  pdf_document:
    keep_tex: TRUE
    template: Tex/TexDefault.txt
    fig_width: 3.5 # Adjust default figure sizes. This can also be done in the chunks of the text.
    fig_height: 3.5
abstract: |
    This document contains the detailed answers for question two of the Financial Econometric exam 2021. 

---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')
# Note: Include = FALSE implies the code is executed, but not printed in your pdf.
# warning and message = FALSE implies ugly messages and warnings are removed from your pdf.
# These should be picked up when you execute the command chunks (code sections below) in your rmd, not printed in your paper!

# Lets load in example data, and see how this can be stored and later called from your 'data' folder.
if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
Example_data <- Texevier::Ex_Dat

# Notice that as you are working in a .Rproj file (I am assuming you are) - the relative paths of your directories start at your specified root.
# This means that when working in a .Rproj file, you never need to use getwd() - it is assumed as your base root automatically.
write_rds(Example_data, path = "data/Example_data.rds")

pacman::p_load(tbl2xts, PerformanceAnalytics)
library(rportfolios)
library(lubridate)
T40 <- read_rds("data/T40.rds")
RebDays <- read_rds("data/Rebalance_days.rds")

```


<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

# Caparing SWIX and ALSI

## Portfolio Return 

```{r}
data1 <- T40 %>% 
    mutate(Tickers = gsub(" SJ Equity", "", Tickers)) %>% 
    arrange(date) %>% 
    mutate(year = as.numeric(format(date, format = "%Y%m"))) %>%
    group_by(year, Tickers) %>%
    filter(date==last(date)) %>%
    ungroup 
    
df_Portf_J400<- 
    data1 %>% select(date,Return, J400) %>% group_by(date) %>% summarise(PortfolioReturn = sum(Return*J400, na.rm =TRUE)) %>% 
      filter(PortfolioReturn != 0)

df_Portf_J200 <- 
    data1 %>% select(date,Return, J200) %>% group_by(date) %>% summarise(PortfolioReturn = sum(Return*J200, na.rm =TRUE)) %>% 
      filter(PortfolioReturn != 0)
      
## CULMULATIVE 
Cum_J400 <- df_Portf_J400 %>% mutate(cumreturn_400 = (cumprod(1 + 
    PortfolioReturn))) %>% # Start at 1
mutate(cumreturn_400 = cumreturn_400/first(cumreturn_400)) %>% 
    select(-PortfolioReturn)

Cum_J200 <- df_Portf_J200 %>% mutate(cumreturn_200 = (cumprod(1 + 
    PortfolioReturn))) %>% mutate(cumreturn_200 = cumreturn_200/first(cumreturn_200)) %>% select(-PortfolioReturn)

Cum_Comp <- left_join(Cum_J400, Cum_J200, by = "date") %>% gather(Type, 
    Value, -date)

# Now let's plot the wealth index (if you invested R100 in
# each) of the two portfolios::

Cum_Comp %>% group_by(Type) %>% ggplot() + geom_line(aes(date, 
    Value, color = Type)) + theme_bw() +theme_bw() +  
    labs(x = "Dates", y = "Return", title = "Portfolio Cumulative Returns", subtitle = "Taking different weight structures into account", caption = "Note:\nOwn Calculations") + guides(col=guide_legend("Portfolios:"))
```
## Caping 

I capped the SWIX to 6 percent and the ALSI to 10 percent (this is how I interpreted the question). 

```{r}
#J400
#max_cap <- 0.6 
#min_cap <- 0 

#rebalance_dates <- as.data.frame(list(RebDays$date))

#rebalance_dates %>%  mutate(datess=as.numeric(lubridate::ymd(date)))

#Weights <- 
  
#data1 %>% mutate(dates=as.numeric(lubridate::ymd(date)))
   # filter(dates %in% as.numeric(rebalance_dates)) %>% 
  
 # group_by(YearMonths, Months, Stocks) %>% filter(Date == last(Date)) %>% ungroup()





#df1 <- data1 %>% select(date, Tickers, Return, J400)
#df1$J400[df1$J400 > 0.06] <- 0.06

#df2 <- data1 %>% select(date, Tickers, Return, J200)
#df2$J200[df2$J200 > 0.1] <- 0.1




```







